### ISSUE TITLE
NoobInCoding's tool needs to add oodle compression

### ISSUE THREAD

**Issue by binlv2012** [rm-NoobInCoding/UnrealUnZen#16]
I tested games using Zlib and it worked, But UE5 uses Oodel compression
I hope you will add it, thank you

**Comment by rm-NoobInCoding** [comment]
Oodle is supported for unpacking..
but for repack im still working on it

**Comment by rm-NoobInCoding** [comment]
Use Oodle compression for repacking is now added to tool.
