### ISSUE TITLE
pack full

### ISSUE THREAD

**Issue by binlv2012** [rm-NoobInCoding/UnrealUnZen#19]
I tried unpacking all files of .utoc, and repack their files. What I mean is pack the entire thing and don't delete any files

And I get this error, any solution

![Untitled 5677- Copy](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/65519230/e5875ee1-e2da-4c53-b34e-9de86c3876b2)

**Comment by BigBoss0674** [comment]
I have the same problem with PC version of Ghostbusters Spirits Unleashed. All files unpacked good, but when i try to pack the same error appears.

**Comment by rm-NoobInCoding** [comment]
Did you test the new version for repack?
I mean, make a patch and the game will read it @BigBoss0674

**Comment by BigBoss0674** [comment]
Yes. Game is reads my modifications. Any ideas why packing speed too slow?

**Comment by binlv2012** [comment]
hey @BigBoss0674 How did you do it? I still get the same error

**Comment by BigBoss0674** [comment]
@binlv2012, hello! Like as usual: Visual Studio 2022 >> Clone Repo >> Make changes that author provided in these two files (this step not needed now because code updated) >> Press F5.

**Comment by rm-NoobInCoding** [comment]
I added new version and you can get it now

**Comment by binlv2012** [comment]
sorry @rm-NoobInCoding , It seems it only supports pack less than 2gb size


![Untitled 5677- Copy](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/65519230/b8cb176a-148f-4f30-802a-89088f479324)
