### ISSUE TITLE
limited to supporting file less than 2GB size

### ISSUE THREAD

**Issue by binlv2012** [rm-NoobInCoding/UnrealUnZen#21]
It seems it only supports pack less than 2gb size, Can it be compressed to a larger size?

![Untitled 5677- Copy](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/65519230/8f064ec5-adac-447c-b58f-3c3984f7fcf4)

**Comment by wolf-5** [comment]
Hello brother, is there a specific way to merge the file because it does not accept file merging

**Comment by wolf-5** [comment]
Is there a specific explanation for merging the file again and returning it to UTOC?
